CREATE TABLE A(
    A1 INTEGER PRIMARY KEY UNIQUE,
    A2 VARCHAR(100)
);

CREATE TABLE B(
    B1 INTEGER PRIMARY KEY UNIQUE,
    B2 INTEGER ,
    B3 VARCHAR(100),
    FOREIGN KEY (B2) REFERENCES A(A1)
);

